FROM node:20-bookworm-slim
WORKDIR /app

# build deps for better-sqlite3
RUN apt-get update && apt-get install -y --no-install-recommends python3 make g++ \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .
EXPOSE 4000
CMD ["node","server.js"]
