FROM node:20-bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends python3 make g++ \
  && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /app/data
COPY package*.json ./
RUN npm ci --omit=dev

COPY . .
EXPOSE 4000
CMD ["node","server.js"]
